# Workflow to build and test wheels
name: Wheel builder
permissions:
  contents: read

on:
  schedule:
    # Nightly build at 3:42 A.M.
    - cron: "42 3 */1 * *"
  push:
    branches:
      - main
      # Release branches
      - ppc_scikit_learn
      - "[0-9]+.[0-9]+.X"
  pull_request:
    branches:
      - main
      - ppc_scikit_learn
      - "[0-9]+.[0-9]+.X"
  # Manual run
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  # Check whether to build the wheels and the source tarball
  check_build_trigger:
    name: Check build trigger
    runs-on: ubuntu-latest
    if: github.repository == 'scikit-learn/scikit-learn' || github.repository == 'PankhudiJ17/scikit-learn'
    outputs:
      build: ${{ steps.check_build_trigger.outputs.build }}

    steps:
      - name: Checkout scikit-learn
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - id: check_build_trigger
        name: Check build trigger
        run: bash build_tools/github/check_build_trigger.sh

  # Build the wheels for Linux, Windows and macOS for Python 3.9 and newer
  build_wheels:
    name: Build wheel for cp${{ matrix.python }}-${{ matrix.platform_id }}-${{ matrix.manylinux_image }}
    runs-on: ${{ matrix.os }}

    # For conda-incubator/setup-miniconda to work
    defaults:
      run:
        shell: bash -el {0}
    needs: check_build_trigger
    if: needs.check_build_trigger.outputs.build

    strategy:
      # Ensure that a wheel builder finishes even if another fails
      fail-fast: false
      matrix:
        include:
          # Window 64 bit
          - os: windows-latest
            python: 39
            platform_id: win_amd64
          - os: windows-latest
            python: 310
            platform_id: win_amd64
          - os: windows-latest
            python: 311
            platform_id: win_amd64
          - os: windows-latest
            python: 312
            platform_id: win_amd64
          - os: windows-latest
            python: 313
            platform_id: win_amd64
          - os: windows-latest
            python: 313t
            platform_id: win_amd64
            free_threaded_support: True

          # Linux 64 bit manylinux2014
          - os: ubuntu-latest
            python: 39
            platform_id: manylinux_x86_64
            manylinux_image: manylinux2014

          # NumPy on Python 3.10 only supports 64bit and is only available with manylinux2014
          - os: ubuntu-latest
            python: 310
            platform_id: manylinux_x86_64
            manylinux_image: manylinux2014

          - os: ubuntu-latest
            python: 311
            platform_id: manylinux_x86_64
            manylinux_image: manylinux2014
          - os: ubuntu-latest
            python: 312
            platform_id: manylinux_x86_64
            manylinux_image: manylinux2014
          - os: ubuntu-latest
            python: 313
            platform_id: manylinux_x86_64
            manylinux_image: manylinux2014
          - os: ubuntu-latest
            python: 313t
            platform_id: manylinux_x86_64
            manylinux_image: manylinux2014
            free_threaded_support: True

          # # Linux 64 bit manylinux2014
          - os: ubuntu-24.04-arm
            python: 39
            platform_id: manylinux_aarch64
            manylinux_image: manylinux2014
          - os: ubuntu-24.04-arm
            python: 310
            platform_id: manylinux_aarch64
            manylinux_image: manylinux2014
          - os: ubuntu-24.04-arm
            python: 311
            platform_id: manylinux_aarch64
            manylinux_image: manylinux2014
          - os: ubuntu-24.04-arm
            python: 312
            platform_id: manylinux_aarch64
            manylinux_image: manylinux2014
          - os: ubuntu-24.04-arm
            python: 313
            platform_id: manylinux_aarch64
            manylinux_image: manylinux2014

          #for ppc64le 
          - os: linux.ppc64le
            python: 39
            platform_id: manylinux_ppc64le
            manylinux_image: manylinux_2_28
          - os: linux.ppc64le
            python: 310
            platform_id: manylinux_ppc64le
            manylinux_image: manylinux_2_28
          - os: linux.ppc64le
            python: 311
            platform_id: manylinux_ppc64le
            manylinux_image: manylinux_2_28
          - os: linux.ppc64le
            python: 312
            platform_id: manylinux_ppc64le
            manylinux_image: manylinux_2_28
          - os: linux.ppc64le
            python: 313
            platform_id: manylinux_ppc64le
            manylinux_image: manylinux_2_28

          # MacOS x86_64
          - os: macos-13
            python: 39
            platform_id: macosx_x86_64
          - os: macos-13
            python: 310
            platform_id: macosx_x86_64
          - os: macos-13
            python: 311
            platform_id: macosx_x86_64
          - os: macos-13
            python: 312
            platform_id: macosx_x86_64
          - os: macos-13
            python: 313
            platform_id: macosx_x86_64
          - os: macos-13
            python: 313t
            platform_id: macosx_x86_64
            free_threaded_support: True

          # MacOS arm64
          - os: macos-14
            python: 39
            platform_id: macosx_arm64
          - os: macos-14
            python: 310
            platform_id: macosx_arm64
          - os: macos-14
            python: 311
            platform_id: macosx_arm64
          - os: macos-14
            python: 312
            platform_id: macosx_arm64
          - os: macos-14
            python: 313
            platform_id: macosx_arm64
          - os: macos-14
            python: 313t
            platform_id: macosx_arm64
            free_threaded_support: True

    steps:
      - name: Checkout scikit-learn
        uses: actions/checkout@v4

      - name: Install Python 3.11
        if:  ${{ matrix.platform_id == 'manylinux_ppc64le' }}
        run: |
          sudo apt-get update
          sudo apt-get install -y python3.11 python3.11-dev python3.11-venv
          sudo update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.11 1
          
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11" # update once build dependencies are available

      - uses: conda-incubator/setup-miniconda@v3
        if: ${{ startsWith(matrix.platform_id, 'macosx') }}
      
      - name: Build and test wheels for ppc64le
        if: ${{ matrix.platform_id == 'manylinux_ppc64le' }}
        env:
          CIBW_CONTAINER_ENGINE: podman
          CIBW_CONTAINER_PRIVILEGED: true   
          CIBW_MANYLINUX_PPC64LE_IMAGE: quay.io/pypa/manylinux_2_28_ppc64le
          CIBW_SKIP: "*-musllinux_ppc64le"
          CIBW_BUILD: cp${{ matrix.python }}-${{ matrix.platform_id }}
          CIBW_BEFORE_BUILD: |
            yum install -y epel-release gcc gcc-c++ gcc-gfortran git wget pkgconfig cmake openssl-devel && \
            wget https://ftp2.osuosl.org/pub/ppc64el/openblas/Openblas_0.3.29_ppc64le.tar.gz && \
            tar -xvpf Openblas_0.3.29_ppc64le.tar.gz -C /usr/local && \
            export PKG_CONFIG_PATH=$PKG_CONFIG_PATH:/usr/local/lib/pkgconfig && \
            bash {project}/build_tools/wheels/cibw_before_build.sh {project}
          CIBW_BEFORE_TEST: |
            yum install -y epel-release gcc gcc-c++ gcc-gfortran git wget pkgconfig cmake openssl-devel && \
            wget https://ftp2.osuosl.org/pub/ppc64el/openblas/Openblas_0.3.29_ppc64le.tar.gz && \
            tar -xvpf Openblas_0.3.29_ppc64le.tar.gz -C /usr/local && \
            export PKG_CONFIG_PATH=$PKG_CONFIG_PATH:/usr/local/lib/pkgconfig && \
            export LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH && \
            ln -sf /usr/local/lib/libopenblas.so.0 /usr/lib64/libopenblas.so.0 && \
            bash {project}/build_tools/wheels/cibw_before_test.sh 
          CIBW_TEST_REQUIRES: pytest pandas
          CIBW_TEST_COMMAND: bash {project}/build_tools/wheels/test_wheels.sh {project}  

        run: bash build_tools/wheels/build_wheels.sh
 
      - name: Build and test wheels
        if: ${{ matrix.platform_id != 'manylinux_ppc64le' }} 
        env:
          CIBW_PRERELEASE_PYTHONS: ${{ matrix.prerelease_pythons }}
          CIBW_FREE_THREADED_SUPPORT: ${{ matrix.free_threaded_support }}
          CIBW_ENVIRONMENT: SKLEARN_SKIP_NETWORK_TESTS=1
          CIBW_BUILD: cp${{ matrix.python }}-${{ matrix.platform_id }}
          CIBW_ARCHS: all
          CIBW_MANYLINUX_X86_64_IMAGE: ${{ matrix.manylinux_image }}
          CIBW_MANYLINUX_I686_IMAGE: ${{ matrix.manylinux_image }}
          # Needed on Windows CI to compile with Visual Studio compiler
          # otherwise Meson detects a MINGW64 platform and use MINGW64
          # toolchain
          CIBW_CONFIG_SETTINGS_WINDOWS: "setup-args=--vsenv"
          CIBW_REPAIR_WHEEL_COMMAND_WINDOWS: bash build_tools/github/repair_windows_wheels.sh {wheel} {dest_dir}
          CIBW_BEFORE_BUILD: bash {project}/build_tools/wheels/cibw_before_build.sh {project}
          CIBW_BEFORE_TEST_WINDOWS: bash build_tools/github/build_minimal_windows_image.sh ${{ matrix.python }}
          CIBW_BEFORE_TEST: bash {project}/build_tools/wheels/cibw_before_test.sh
          CIBW_ENVIRONMENT_PASS_LINUX: RUNNER_OS
          CIBW_TEST_REQUIRES: pytest pandas
          # On Windows, we use a custom Docker image and CIBW_TEST_REQUIRES_WINDOWS
          # does not make sense because it would install dependencies in the host
          # rather than inside the Docker image
          CIBW_TEST_REQUIRES_WINDOWS: ""
          CIBW_TEST_COMMAND: bash {project}/build_tools/wheels/test_wheels.sh {project}
          CIBW_TEST_COMMAND_WINDOWS: bash {project}/build_tools/github/test_windows_wheels.sh ${{ matrix.python }} {project}
          CIBW_BUILD_VERBOSITY: 1

        run: bash build_tools/wheels/build_wheels.sh

      - name: Store artifacts
        uses: actions/upload-artifact@v4
        with:
          name: cibw-wheels-cp${{ matrix.python }}-${{ matrix.platform_id }}
          path: wheelhouse/*.whl

  update-tracker:
    uses: ./.github/workflows/update_tracking_issue.yml
    if: ${{ always() }}
    needs: [build_wheels]
    with:
      job_status: ${{ needs.build_wheels.result }}
    secrets:
      BOT_GITHUB_TOKEN: ${{ secrets.BOT_GITHUB_TOKEN }}

  # Build the source distribution under Linux
  build_sdist:
    name: Source distribution
    runs-on: ubuntu-latest
    needs: check_build_trigger
    if: needs.check_build_trigger.outputs.build

    steps:
      - name: Checkout scikit-learn
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9" # update once build dependencies are available

      - name: Build source distribution
        run: bash build_tools/github/build_source.sh

      - name: Test source distribution
        run: bash build_tools/github/test_source.sh
        env:
          SKLEARN_SKIP_NETWORK_TESTS: 1

      - name: Store artifacts
        uses: actions/upload-artifact@v4
        with:
          name: cibw-sdist
          path: dist/*.tar.gz

  # Upload the wheels and the source distribution
  upload_anaconda:
    name: Upload to Anaconda
    runs-on: ubuntu-latest
    environment: upload_anaconda
    needs: [build_wheels, build_sdist]
    # The artifacts cannot be uploaded on PRs
    if: github.event_name != 'pull_request'

    steps:
      - name: Checkout scikit-learn
        uses: actions/checkout@v4

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: cibw-*
          path: dist
          merge-multiple: true

      - name: Setup Python
        uses: actions/setup-python@v5

      - name: Upload artifacts
        env:
          # Secret variables need to be mapped to environment variables explicitly
          SCIKIT_LEARN_NIGHTLY_UPLOAD_TOKEN: ${{ secrets.SCIKIT_LEARN_NIGHTLY_UPLOAD_TOKEN }}
          SCIKIT_LEARN_STAGING_UPLOAD_TOKEN: ${{ secrets.SCIKIT_LEARN_STAGING_UPLOAD_TOKEN }}
          ARTIFACTS_PATH: dist
        # Force a replacement if the remote file already exists
        run: bash build_tools/github/upload_anaconda.sh

# # Workflow to build and test wheels
# name: Wheel builder
# permissions:
#   contents: read

# on:
#   schedule:
#     # Nightly build at 3:42 A.M.
#     - cron: "42 3 */1 * *"
#   push:
#     branches:
#       - main
#       # Release branches
#       - "[0-9]+.[0-9]+.X"
#       - ppc_scikit_learn
#   pull_request:
#     branches:
#       - main
#       - "[0-9]+.[0-9]+.X"
#   # Manual run
#   workflow_dispatch:

# concurrency:
#   group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
#   cancel-in-progress: true

# jobs:
#   # Check whether to build the wheels and the source tarball
#   check_build_trigger:
#     name: Check build trigger
#     runs-on: ubuntu-latest
#     if: github.repository == 'scikit-learn/scikit-learn' || github.repository == 'PankhudiJ17/scikit-learn'
#     outputs:
#       build: ${{ steps.check_build_trigger.outputs.build }}

#     steps:
#       - name: Checkout scikit-learn
#         uses: actions/checkout@v4
#         with:
#           ref: ${{ github.event.pull_request.head.sha }}

#       - id: check_build_trigger
#         name: Check build trigger
#         run: bash build_tools/github/check_build_trigger.sh

#   # Build the wheels for Linux, Windows and macOS for Python 3.9 and newer
#   build_wheels:
#     name: Build wheel for cp${{ matrix.python }}-${{ matrix.platform_id }}-${{ matrix.manylinux_image }}
#    # runs-on: linux.ppc64le
#     #${{ matrix.os }}
#     runs-on: ${{ matrix.os }}
#     # For conda-incubator/setup-miniconda to work
#     defaults:
#       run:
#         shell: bash -el {0}
#     needs: check_build_trigger
#     if: needs.check_build_trigger.outputs.build

#     strategy:
#       # Ensure that a wheel builder finishes even if another fails
#       fail-fast: false
#       matrix:
#         include:
#           #Window 64 bit
#           # - os: windows-latest
#           #   python: 39
#           #   platform_id: win_amd64
#           # - os: windows-latest
#           #   python: 310
#           #   platform_id: win_amd64
#           # - os: windows-latest
#           #   python: 311
#           #   platform_id: win_amd64
#           # - os: windows-latest
#           #   python: 312
#           #   platform_id: win_amd64
#           # - os: windows-latest
#           #   python: 313
#           #   platform_id: win_amd64
#           # - os: windows-latest
#           #   python: 313t
#           #   platform_id: win_amd64
#           #   free_threaded_support: True

#           # # Linux 64 bit manylinux2014
#           # - os: ubuntu-latest
#           #   python: 39
#           #   platform_id: manylinux_x86_64
#           #   manylinux_image: manylinux2014

#           # # NumPy on Python 3.10 only supports 64bit and is only available with manylinux2014
#           # - os: ubuntu-latest
#           #   python: 310
#           #   platform_id: manylinux_x86_64
#           #   manylinux_image: manylinux2014

#           # - os: ubuntu-latest
#           #   python: 311
#           #   platform_id: manylinux_x86_64
#           #   manylinux_image: manylinux2014
#           # - os: ubuntu-latest
#           #   python: 312
#           #   platform_id: manylinux_x86_64
#           #   manylinux_image: manylinux2014
#           # - os: ubuntu-latest
#           #   python: 313
#           #   platform_id: manylinux_x86_64
#           #   manylinux_image: manylinux2014
#           # - os: ubuntu-latest
#           #   python: 313t
#           #   platform_id: manylinux_x86_64
#           #   manylinux_image: manylinux2014
#           #   free_threaded_support: True

#           # # # Linux 64 bit manylinux2014
#           # - os: ubuntu-24.04-arm
#           #   python: 39
#           #   platform_id: manylinux_aarch64
#           #   manylinux_image: manylinux2014
#           # - os: ubuntu-24.04-arm
#           #   python: 310
#           #   platform_id: manylinux_aarch64
#           #   manylinux_image: manylinux2014
#           # - os: ubuntu-24.04-arm
#           #   python: 311
#           #   platform_id: manylinux_aarch64
#           #   manylinux_image: manylinux2014
#           # - os: ubuntu-24.04-arm
#           #   python: 312
#           #   platform_id: manylinux_aarch64
#           #   manylinux_image: manylinux2014
#           # - os: ubuntu-24.04-arm
#           #   python: 313
#           #   platform_id: manylinux_aarch64
#           #   manylinux_image: manylinux2014

#           # #for pc64le
#           - os: linux.ppc64le #github runner , dnt have for ppc , we use self hosted runner coz we dont hve for ppc
#             python: 39
#             platform_id: manylinux_ppc64le
#             manylinux_image: manylinux_2_28

#           - os: linux.ppc64le
#             python: 310
#             platform_id: manylinux_ppc64le
#             manylinux_image: manylinux_2_28
          
#           - os: linux.ppc64le
#             python: 311
#             platform_id: manylinux_ppc64le
#             manylinux_image: manylinux_2_28

#           - os: linux.ppc64le
#             python: 312
#             platform_id: manylinux_ppc64le
#             manylinux_image: manylinux_2_28
            
#           - os: linux.ppc64le
#             python: 313
#             platform_id: manylinux_ppc64le
#             manylinux_image: manylinux_2_28


#           # MacOS x86_64
#           # - os: macos-13
#           #   python: 39
#           #   platform_id: macosx_x86_64
#           # - os: macos-13
#           #   python: 310
#           #   platform_id: macosx_x86_64
#           # - os: macos-13
#           #   python: 311
#           #   platform_id: macosx_x86_64
#           # - os: macos-13
#           #   python: 312
#           #   platform_id: macosx_x86_64
#           # - os: macos-13
#           #   python: 313
#           #   platform_id: macosx_x86_64
#           # - os: macos-13
#           #   python: 313t
#           #   platform_id: macosx_x86_64
#           #   free_threaded_support: True

#           # # MacOS arm64
#           # - os: macos-14
#           #   python: 39
#           #   platform_id: macosx_arm64
#           # - os: macos-14
#           #   python: 310
#           #   platform_id: macosx_arm64
#           # - os: macos-14
#           #   python: 311
#           #   platform_id: macosx_arm64
#           # - os: macos-14
#           #   python: 312
#           #   platform_id: macosx_arm64
#           # - os: macos-14
#           #   python: 313
#           #   platform_id: macosx_arm64
#           # - os: macos-14
#           #   python: 313t
#           #   platform_id: macosx_arm64
#           #   free_threaded_support: True

#     steps:
#       #- name: Set up QEMU
#       #  uses: docker/setup-qemu-action@v3
#       #  with:
#       #    platforms: ppc64le 
#       - name: Checkout scikit-learn
#         uses: actions/checkout@v4

       
#       - name: Install Python 3.11
#         if:  ${{ matrix.platform_id == 'manylinux_ppc64le' }}
#         run: |
#           sudo apt-get update
#           sudo apt-get install -y python3.11 python3.11-dev python3.11-venv
#           sudo update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.11 1
#           python3 --version
          
#       # - name: Setup Python
#       #   uses: actions/setup-python@v5
#       #   with:
#       #     python-version: "3.11" # update once build dependencies are available

#       - uses: conda-incubator/setup-miniconda@v3
#         if: ${{ startsWith(matrix.platform_id, 'macosx') }}

#       - name: Build ppc64le wheel
#         if: ${{ matrix.platform_id == 'manylinux_ppc64le' }}
#         env: 
#           CIBW_CONTAINER_ENGINE: podman
#           CIBW_CONTAINER_PRIVILEGED: true
#           CIBW_BUILD: cp${{ matrix.python }}-${{ matrix.platform_id }}
#           CIBW_MANYLINUX_PPC64LE_IMAGE: quay.io/pypa/manylinux_2_28_ppc64le
#           CIBW_SKIP: "*-musllinux_ppc64le"
#           CIBW_ENVIRONMENT_PASS_LINUX: RUNNER_OS
#           CIBW_BEFORE_BUILD: |
#             yum install -y epel-release gcc gcc-c++ gcc-gfortran git wget pkgconfig cmake openssl-devel && \
#             wget https://ftp2.osuosl.org/pub/ppc64el/openblas/Openblas_0.3.29_ppc64le.tar.gz && \
#             tar -xvpf Openblas_0.3.29_ppc64le.tar.gz -C /usr/local && \
#             export PKG_CONFIG_PATH=$PKG_CONFIG_PATH:/usr/local/lib/pkgconfig && \
#             bash {project}/build_tools/wheels/cibw_before_build.sh {project}
#           CIBW_BEFORE_TEST: |
#             yum install -y epel-release gcc gcc-c++ gcc-gfortran git wget pkgconfig cmake openssl-devel && \
#             pip3 install scipy-openblas64
#             wget https://ftp2.osuosl.org/pub/ppc64el/openblas/Openblas_0.3.29_ppc64le.tar.gz && \
#             tar -xvpf Openblas_0.3.29_ppc64le.tar.gz -C /usr/local && \
#             export PKG_CONFIG_PATH=$PKG_CONFIG_PATH:/usr/local/lib/pkgconfig && \
#             export LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH && \
#             ln -sf /usr/local/lib/libopenblas.so.0 /usr/lib64/libopenblas.so.0 && \
#             bash {project}/build_tools/wheels/cibw_before_test.sh  
#         run: bash build_tools/wheels/build_wheels.sh
#             # sudo apt-get update
#             # sudo apt-get install -y python3.11 python3.11-dev python3.11-venv
#             # sudo update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.11 1
#             # python3 --version 
#             # bash build_tools/wheels/build_wheels.sh
           
#       - name: Build and test wheels
#         if: ${{ matrix.platform_id != 'manylinux_ppc64le' }}
#         env:
#           #CIBW_CONTAINER_ENGINE: podman
#           #CIBW_CONTAINER_PRIVILEGED: true
#           CIBW_PRERELEASE_PYTHONS: ${{ matrix.prerelease_pythons }}
#           CIBW_FREE_THREADED_SUPPORT: ${{ matrix.free_threaded_support }}
#           CIBW_ENVIRONMENT: SKLEARN_SKIP_NETWORK_TESTS=1
#           CIBW_BUILD: cp${{ matrix.python }}-${{ matrix.platform_id }}
#           CIBW_ARCHS: all
#           CIBW_MANYLINUX_X86_64_IMAGE: ${{ matrix.manylinux_image }}
#           CIBW_MANYLINUX_I686_IMAGE: ${{ matrix.manylinux_image }}
#           # Needed on Windows CI to compile with Visual Studio compiler
#           # otherwise Meson detects a MINGW64 platform and use MINGW64
#           # toolchain

#           # CIBW_MANYLINUX_PPC64LE_IMAGE: quay.io/pypa/manylinux_2_28_ppc64le
#           # CIBW_SKIP: "*-musllinux_ppc64le"

#           # CIBW_BEFORE_BUILD: |
#           #   # yum install -y epel-release gcc gcc-c++ gcc-gfortran git wget pkgconfig cmake openssl-devel && \
#           #   # wget https://ftp2.osuosl.org/pub/ppc64el/openblas/Openblas_0.3.29_ppc64le.tar.gz && \
#           #   # tar -xvpf Openblas_0.3.29_ppc64le.tar.gz -C /usr/local && \
#           #   # export PKG_CONFIG_PATH=$PKG_CONFIG_PATH:/usr/local/lib/pkgconfig && \
#           #   # bash {project}/build_tools/wheels/cibw_before_build.sh {project}
#           CIBW_CONFIG_SETTINGS_WINDOWS: "setup-args=--vsenv"
#           CIBW_REPAIR_WHEEL_COMMAND_WINDOWS: bash build_tools/github/repair_windows_wheels.sh {wheel} {dest_dir}
#           CIBW_BEFORE_BUILD: bash {project}/build_tools/wheels/cibw_before_build.sh {project}
#           CIBW_BEFORE_TEST_WINDOWS: bash build_tools/github/build_minimal_windows_image.sh ${{ matrix.python }}
#           # CIBW_BEFORE_TEST: |
#           #   yum install -y epel-release gcc gcc-c++ gcc-gfortran git wget pkgconfig cmake openssl-devel && \
#           #   pip3 install scipy-openblas64
#           #   wget https://ftp2.osuosl.org/pub/ppc64el/openblas/Openblas_0.3.29_ppc64le.tar.gz && \
#           #   tar -xvpf Openblas_0.3.29_ppc64le.tar.gz -C /usr/local && \
#           #   export PKG_CONFIG_PATH=$PKG_CONFIG_PATH:/usr/local/lib/pkgconfig && \
#           #   export LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH && \
#           #   ln -sf /usr/local/lib/libopenblas.so.0 /usr/lib64/libopenblas.so.0 && \
#           #   bash {project}/build_tools/wheels/cibw_before_test.sh
#           CIBW_BEFORE_TEST: bash {project}/build_tools/wheels/cibw_before_test.sh 
#           CIBW_ENVIRONMENT_PASS_LINUX: RUNNER_OS
                      
#           CIBW_TEST_REQUIRES: pytest pandas
           
#           CIBW_TEST_REQUIRES_WINDOWS: ""

#           CIBW_TEST_COMMAND: bash {project}/build_tools/wheels/test_wheels.sh {project}
#           CIBW_TEST_COMMAND_WINDOWS: bash {project}/build_tools/github/test_windows_wheels.sh ${{ matrix.python }} {project}
#           CIBW_BUILD_VERBOSITY: 1

#         run: bash build_tools/wheels/build_wheels.sh

      
#       - name: Store artifacts
#         uses: actions/upload-artifact@v4
#         with:
#           name: cibw-wheels-cp${{ matrix.python }}-${{ matrix.platform_id }}
#           path: wheelhouse/*.whl

#   update-tracker:
#     uses: ./.github/workflows/update_tracking_issue.yml
#     if: ${{ always() }}
#     needs: [build_wheels]
#     with:
#       job_status: ${{ needs.build_wheels.result }}
#     secrets:
#       BOT_GITHUB_TOKEN: ${{ secrets.BOT_GITHUB_TOKEN }}

#   # Build the source distribution under Linux
#   build_sdist:
#     name: Source distribution
#     runs-on: ubuntu-latest
#     needs: check_build_trigger
#     if: needs.check_build_trigger.outputs.build

#     steps:
#       - name: Checkout scikit-learn
#         uses: actions/checkout@v4

#       - name: Setup Python
#         uses: actions/setup-python@v5
#         with:
#           python-version: "3.9" # update once build dependencies are available

#       - name: Build source distribution
#         run: bash build_tools/github/build_source.sh

#       - name: Test source distribution
#         run: bash build_tools/github/test_source.sh
#         env:
#           SKLEARN_SKIP_NETWORK_TESTS: 1

#       - name: Store artifacts
#         uses: actions/upload-artifact@v4
#         with:
#           name: cibw-sdist
#           path: dist/*.tar.gz

#   # Upload the wheels and the source distribution
#   upload_anaconda:
#     name: Upload to Anaconda
#     runs-on: ubuntu-latest
#     environment: upload_anaconda
#     needs: [build_wheels, build_sdist]
#     # The artifacts cannot be uploaded on PRs
#     if: github.event_name != 'pull_request'

#     steps:
#       - name: Checkout scikit-learn
#         uses: actions/checkout@v4

#       - name: Download artifacts
#         uses: actions/download-artifact@v4
#         with:
#           pattern: cibw-*
#           path: dist
#           merge-multiple: true

#       - name: Setup Python
#         uses: actions/setup-python@v5

#       - name: Upload artifacts
#         env:
#           # Secret variables need to be mapped to environment variables explicitly
#           SCIKIT_LEARN_NIGHTLY_UPLOAD_TOKEN: ${{ secrets.SCIKIT_LEARN_NIGHTLY_UPLOAD_TOKEN }}
#           SCIKIT_LEARN_STAGING_UPLOAD_TOKEN: ${{ secrets.SCIKIT_LEARN_STAGING_UPLOAD_TOKEN }}
#           ARTIFACTS_PATH: dist
#         # Force a replacement if the remote file already exists
#         run: bash build_tools/github/upload_anaconda.sh

#-------QEMU---------





# name: Wheel builder
# permissions:
#   contents: read

# on:
#   schedule:
#     # Nightly build at 3:42 A.M.
#     - cron: "42 3 */1 * *"
#   push:
#     branches:
#       - main
#       # Release branches
#       - ppc_scikit_learn
#       - "[0-9]+.[0-9]+.X"
#   pull_request:
#     branches:
#       - main
#       - ppc_scikit_learn
#       - "[0-9]+.[0-9]+.X"
#   # Manual run
#   workflow_dispatch:

# concurrency:
#   group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
#   cancel-in-progress: true

# jobs:
#   # Check whether to build the wheels and the source tarball
#   #check_build_trigger:
#    # name: Check build trigger
#    # runs-on: ubuntu-latest
#    # if: github.repository == 'scikit-learn/scikit-learn' || github.repository == 'PankhudiJ17/scikit-learn'
#    # outputs:
#    #   build: ${{ steps.check_build_trigger.outputs.build }}

#     #steps:
#     #  - name: Checkout scikit-learn
#     #    uses: actions/checkout@v4
#     #    with:
#     #      ref: ${{ github.event.pull_request.head.sha }}

#     #  - id: check_build_trigger
#     #    name: Check build trigger
#     #    run: bash build_tools/github/check_build_trigger.sh

#   # Build the wheels for Linux, Windows and macOS for Python 3.9 and newer

 

#   build_wheels:
#     name: Build wheel for cp${{ matrix.python }}-${{ matrix.platform_id }}-${{ matrix.manylinux_image }}
#     runs-on: ${{ matrix.os }}

#     # For conda-incubator/setup-miniconda to work
#     # defaults:
#     #   run:
#     #     shell: bash -el {0}
#     # needs: check_build_trigger
#     # if: needs.check_build_trigger.outputs.build

#     strategy:
#       # Ensure that a wheel builder finishes even if another fails
#       fail-fast: false
#       matrix:
#         include:
#           # Window 64 bit
#         #  - os: windows-latest
#         #    python: 39
#         #    platform_id: win_amd64
#         #  - os: windows-latest
#         #    python: 310
#         #    platform_id: win_amd64
#         #  - os: windows-latest
#         #    python: 311
#         #    platform_id: win_amd64
#         #  - os: windows-latest
#         #    python: 312
#         #    platform_id: win_amd64
#         #  - os: windows-latest
#         #    python: 313
#         #    platform_id: win_amd64
#         #  - os: windows-latest
#         #    python: 313t
#         #    platform_id: win_amd64
#         #    free_threaded_support: True

#           # Linux 64 bit manylinux2014
#           # - os: ubuntu-latest
#           #   python: 39
#           #   platform_id: manylinux_x86_64
#           #   manylinux_image: manylinux2014

#           # NumPy on Python 3.10 only supports 64bit and is only available with manylinux2014
#           # - os: ubuntu-latest
#           #   python: 310
#           #   platform_id: manylinux_x86_64
#           #   manylinux_image: manylinux2014
          
#           - os: ubuntu-latest
#             python: 39
#             platform_id: manylinux_ppc64le
#             manylinux_image: manylinux_2_28

#           - os: ubuntu-latest
#             python: 310
#             platform_id: manylinux_ppc64le
#             manylinux_image: manylinux_2_28
          
#           - os: ubuntu-latest
#             python: 311
#             platform_id: manylinux_ppc64le
#             manylinux_image: manylinux_2_28

#           - os: ubuntu-latest
#             python: 312
#             platform_id: manylinux_ppc64le
#             manylinux_image: manylinux_2_28

#           - os: ubuntu-latest
#             python: 313
#             platform_id: manylinux_ppc64le
#             manylinux_image: manylinux_2_28
  
#           # - os: ubuntu-latest
#           #   python: 311
#           #   platform_id: manylinux_x86_64
#           #   manylinux_image: manylinux2014
#           # - os: ubuntu-latest
#           #   python: 312
#           #   platform_id: manylinux_x86_64
#           #   manylinux_image: manylinux2014
#           # - os: ubuntu-latest
#           #   python: 313
#           #   platform_id: manylinux_x86_64
#           #   manylinux_image: manylinux2014
#           # - os: ubuntu-latest
#           #   python: 313t
#           #   platform_id: manylinux_x86_64
#           #   manylinux_image: manylinux2014
#           #   free_threaded_support: True

#           # # Linux 64 bit manylinux2014
#           # - os: ubuntu-24.04-arm
#           #   python: 39
#           #   platform_id: manylinux_aarch64
#           #   manylinux_image: manylinux2014
#           # - os: ubuntu-24.04-arm
#           #   python: 310
#           #   platform_id: manylinux_aarch64
#           #   manylinux_image: manylinux2014
#           # - os: ubuntu-24.04-arm
#           #   python: 311
#           #   platform_id: manylinux_aarch64
#           #   manylinux_image: manylinux2014
#           # - os: ubuntu-24.04-arm
#           #   python: 312
#           #   platform_id: manylinux_aarch64
#           #   manylinux_image: manylinux2014
#           # - os: ubuntu-24.04-arm
#           #   python: 313
#           #   platform_id: manylinux_aarch64
#           #   manylinux_image: manylinux2014

#           # MacOS x86_64
#           # - os: macos-13
#           #   python: 39
#           #   platform_id: macosx_x86_64
#           # - os: macos-13
#           #   python: 310
#           #   platform_id: macosx_x86_64
#           # - os: macos-13
#           #   python: 311
#           #   platform_id: macosx_x86_64
#           # - os: macos-13
#           #   python: 312
#           #   platform_id: macosx_x86_64
#           # - os: macos-13
#           #   python: 313
#           #   platform_id: macosx_x86_64
#           # - os: macos-13
#           #   python: 313t
#           #   platform_id: macosx_x86_64
#           #   free_threaded_support: True

#           # MacOS arm64
#           # - os: macos-14
#           #   python: 39
#           #   platform_id: macosx_arm64
#           # - os: macos-14
#           #   python: 310
#           #   platform_id: macosx_arm64
#           # - os: macos-14
#           #   python: 311
#           #   platform_id: macosx_arm64
#           # - os: macos-14
#           #   python: 312
#           #   platform_id: macosx_arm64
#           # - os: macos-14
#           #   python: 313
#           #   platform_id: macosx_arm64
#           # - os: macos-14
#           #   python: 313t
#           #   platform_id: macosx_arm64
#           #   free_threaded_support: True
#     steps:
#       - name: Set up QEMU
#         uses: docker/setup-qemu-action@v3
#         with:
#           platforms: ppc64le 
#       - name: Checkout scikit-learn
#         uses: actions/checkout@v4

#       - name: Setup Python
#         uses: actions/setup-python@v5
#         with:
#           python-version: "3.11" # update once build dependencies are available

#       - uses: conda-incubator/setup-miniconda@v3
#         if: ${{ startsWith(matrix.platform_id, 'macosx') }}

#       - name: Build and test wheels
#         env:
#           CIBW_PRERELEASE_PYTHONS: ${{ matrix.prerelease_pythons }}
#           CIBW_FREE_THREADED_SUPPORT: ${{ matrix.free_threaded_support }}
#           CIBW_ENVIRONMENT: SKLEARN_SKIP_NETWORK_TESTS=1
#           CIBW_BUILD: cp${{ matrix.python }}-${{ matrix.platform_id }}
#           CIBW_ARCHS: all
#           CIBW_MANYLINUX_X86_64_IMAGE: ${{ matrix.manylinux_image }}
#           CIBW_MANYLINUX_I686_IMAGE: ${{ matrix.manylinux_image }}

#           CIBW_MANYLINUX_PPC64LE_IMAGE: ${{ matrix.manylinux_image }}
#           CIBW_SKIP: "*-musllinux_ppc64le"

#           #CIBW_MUSLLINUX_PPC64LE_IMAGE: quay.io/pypa/musllinux_1_2_ppc64le

#           # Needed on Windows CI to compile with Visual Studio compiler
#           # otherwise Meson detects a MINGW64 platform and use MINGW64
#           # toolchain
#           CIBW_CONFIG_SETTINGS_WINDOWS: "setup-args=--vsenv"
#           CIBW_REPAIR_WHEEL_COMMAND_WINDOWS: bash build_tools/github/repair_windows_wheels.sh {wheel} {dest_dir}
          
#           #CIBW_BEFORE_BUILD: "yum install -y epel-release gcc gcc-c++ gcc-gfortran git wget pkgconfig cmake && wget https://ftp2.osuosl.org/pub/ppc64el/openblas/Openblas_0.3.29_ppc64le.tar.gz && tar -xvpf Openblas_0.3.29_ppc64le.tar.gz -C /usr/local && export PKG_CONFIG_PATH=$PKG_CONFIG_PATH:/usr/local/lib/pkgconfig"
#           CIBW_BEFORE_BUILD: |
#              yum install -y epel-release gcc gcc-c++ gcc-gfortran git wget pkgconfig cmake openssl-devel && \
#              wget https://ftp2.osuosl.org/pub/ppc64el/openblas/Openblas_0.3.29_ppc64le.tar.gz && \
#              tar -xvpf Openblas_0.3.29_ppc64le.tar.gz -C /usr/local && \
#              export PKG_CONFIG_PATH=$PKG_CONFIG_PATH:/usr/local/lib/pkgconfig && \
#              bash {project}/build_tools/wheels/cibw_before_build.sh {project} 

#           #CIBW_BEFORE_BUILD: bash {project}/build_tools/wheels/cibw_before_build.sh {project}
#           CIBW_BEFORE_TEST_WINDOWS: bash build_tools/github/build_minimal_windows_image.sh ${{ matrix.python }}
#           CIBW_BEFORE_TEST: bash {project}/build_tools/wheels/cibw_before_test.sh
#           CIBW_ENVIRONMENT_PASS_LINUX: RUNNER_OS
#           CIBW_TEST_REQUIRES: pytest pandas
#           # On Windows, we use a custom Docker image and CIBW_TEST_REQUIRES_WINDOWS
#           # does not make sense because it would install dependencies in the host
#           # rather than inside the Docker image
#           CIBW_TEST_REQUIRES_WINDOWS: ""
#           #CIBW_TEST_COMMAND: bash {project}/build_tools/wheels/test_wheels.sh {project}
#           CIBW_BEFORE_TEST: |
#              yum install -y epel-release gcc gcc-c++ gcc-gfortran git wget pkgconfig cmake openssl-devel && \
#              pip3 install scipy-openblas64
#              wget https://ftp2.osuosl.org/pub/ppc64el/openblas/Openblas_0.3.29_ppc64le.tar.gz && \
#              tar -xvpf Openblas_0.3.29_ppc64le.tar.gz -C /usr/local && \
#              export PKG_CONFIG_PATH=$PKG_CONFIG_PATH:/usr/local/lib/pkgconfig && \
#              export LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH && \
#              ln -sf /usr/local/lib/libopenblas.so.0 /usr/lib64/libopenblas.so.0 && \
#              bash {project}/build_tools/wheels/cibw_before_test.sh
#           CIBW_TEST_COMMAND_WINDOWS: bash {project}/build_tools/github/test_windows_wheels.sh ${{ matrix.python }} {project}
#           CIBW_BUILD_VERBOSITY: 1

#         run: bash build_tools/wheels/build_wheels.sh

#       - name: Store artifacts
#         uses: actions/upload-artifact@v4
#         with:
#           name: cibw-wheels-cp${{ matrix.python }}-${{ matrix.platform_id }}
#           path: wheelhouse/*.whl

#   update-tracker:
#     uses: ./.github/workflows/update_tracking_issue.yml
#     if: ${{ always() }}
#     needs: [build_wheels]
#     with:
#       job_status: ${{ needs.build_wheels.result }}
#     secrets:
#       BOT_GITHUB_TOKEN: ${{ secrets.BOT_GITHUB_TOKEN }}






#========================10-03-25======================

# # Workflow to build and test wheels
# name: Wheel builder
# permissions:
#   contents: read

# on:
#   schedule:
#     # Nightly build at 3:42 A.M.
#     - cron: "42 3 */1 * *"
#   push:
#     branches:
#       - main
#       # Release branches
#       - "[0-9]+.[0-9]+.X"
#       - ppc_scikit_learn
#   pull_request:
#     branches:
#       - main
#       - "[0-9]+.[0-9]+.X"
#   # Manual run
#   workflow_dispatch:

# concurrency:
#   group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
#   cancel-in-progress: true

# jobs:
#   # Check whether to build the wheels and the source tarball
#   check_build_trigger:
#     name: Check build trigger
#     runs-on: ubuntu-latest
#     if: github.repository == 'scikit-learn/scikit-learn' || github.repository == 'PankhudiJ17/scikit-learn'
#     outputs:
#       build: ${{ steps.check_build_trigger.outputs.build }}

#     steps:
#       - name: Checkout scikit-learn
#         uses: actions/checkout@v4
#         with:
#           ref: ${{ github.event.pull_request.head.sha }}

#       - id: check_build_trigger
#         name: Check build trigger
#         run: bash build_tools/github/check_build_trigger.sh

#   # Build the wheels for Linux, Windows and macOS for Python 3.9 and newer
#   build_wheels:
#     name: Build wheel for cp${{ matrix.python }}-${{ matrix.platform_id }}-${{ matrix.manylinux_image }}
#    # runs-on: linux.ppc64le
#     #${{ matrix.os }}
#     runs-on: ${{ matrix.os }}
#     # For conda-incubator/setup-miniconda to work
#     defaults:
#       run:
#         shell: bash -el {0}
#     needs: check_build_trigger
#     if: needs.check_build_trigger.outputs.build

#     strategy:
#       # Ensure that a wheel builder finishes even if another fails
#       fail-fast: false
#       matrix:
#         include:
#           #Window 64 bit
#           # - os: windows-latest
#           #   python: 39
#           #   platform_id: win_amd64
#           # - os: windows-latest
#           #   python: 310
#           #   platform_id: win_amd64
#           # - os: windows-latest
#           #   python: 311
#           #   platform_id: win_amd64
#           # - os: windows-latest
#           #   python: 312
#           #   platform_id: win_amd64
#           # - os: windows-latest
#           #   python: 313
#           #   platform_id: win_amd64
#           # - os: windows-latest
#           #   python: 313t
#           #   platform_id: win_amd64
#           #   free_threaded_support: True

#           # # Linux 64 bit manylinux2014
#           # - os: ubuntu-latest
#           #   python: 39
#           #   platform_id: manylinux_x86_64
#           #   manylinux_image: manylinux2014

#           # # NumPy on Python 3.10 only supports 64bit and is only available with manylinux2014
#           # - os: ubuntu-latest
#           #   python: 310
#           #   platform_id: manylinux_x86_64
#           #   manylinux_image: manylinux2014

#           # - os: ubuntu-latest
#           #   python: 311
#           #   platform_id: manylinux_x86_64
#           #   manylinux_image: manylinux2014
#           # - os: ubuntu-latest
#           #   python: 312
#           #   platform_id: manylinux_x86_64
#           #   manylinux_image: manylinux2014
#           # - os: ubuntu-latest
#           #   python: 313
#           #   platform_id: manylinux_x86_64
#           #   manylinux_image: manylinux2014
#           # - os: ubuntu-latest
#           #   python: 313t
#           #   platform_id: manylinux_x86_64
#           #   manylinux_image: manylinux2014
#           #   free_threaded_support: True

#           # # # Linux 64 bit manylinux2014
#           # - os: ubuntu-24.04-arm
#           #   python: 39
#           #   platform_id: manylinux_aarch64
#           #   manylinux_image: manylinux2014
#           # - os: ubuntu-24.04-arm
#           #   python: 310
#           #   platform_id: manylinux_aarch64
#           #   manylinux_image: manylinux2014
#           # - os: ubuntu-24.04-arm
#           #   python: 311
#           #   platform_id: manylinux_aarch64
#           #   manylinux_image: manylinux2014
#           # - os: ubuntu-24.04-arm
#           #   python: 312
#           #   platform_id: manylinux_aarch64
#           #   manylinux_image: manylinux2014
#           # - os: ubuntu-24.04-arm
#           #   python: 313
#           #   platform_id: manylinux_aarch64
#           #   manylinux_image: manylinux2014

#           # #for pc64le
#           - os: linux.ppc64le #github runner , dnt have for ppc , we use self hosted runner coz we dont hve for ppc
#             python: 39
#             platform_id: manylinux_ppc64le
#             manylinux_image: manylinux_2_28

#           - os: linux.ppc64le
#             python: 310
#             platform_id: manylinux_ppc64le
#             manylinux_image: manylinux_2_28
          
#           - os: linux.ppc64le
#             python: 311
#             platform_id: manylinux_ppc64le
#             manylinux_image: manylinux_2_28

#           - os: linux.ppc64le
#             python: 312
#             platform_id: manylinux_ppc64le
#             manylinux_image: manylinux_2_28
            
#           - os: linux.ppc64le
#             python: 313
#             platform_id: manylinux_ppc64le
#             manylinux_image: manylinux_2_28


#           # MacOS x86_64
#           # - os: macos-13
#           #   python: 39
#           #   platform_id: macosx_x86_64
#           # - os: macos-13
#           #   python: 310
#           #   platform_id: macosx_x86_64
#           # - os: macos-13
#           #   python: 311
#           #   platform_id: macosx_x86_64
#           # - os: macos-13
#           #   python: 312
#           #   platform_id: macosx_x86_64
#           # - os: macos-13
#           #   python: 313
#           #   platform_id: macosx_x86_64
#           # - os: macos-13
#           #   python: 313t
#           #   platform_id: macosx_x86_64
#           #   free_threaded_support: True

#           # # MacOS arm64
#           # - os: macos-14
#           #   python: 39
#           #   platform_id: macosx_arm64
#           # - os: macos-14
#           #   python: 310
#           #   platform_id: macosx_arm64
#           # - os: macos-14
#           #   python: 311
#           #   platform_id: macosx_arm64
#           # - os: macos-14
#           #   python: 312
#           #   platform_id: macosx_arm64
#           # - os: macos-14
#           #   python: 313
#           #   platform_id: macosx_arm64
#           # - os: macos-14
#           #   python: 313t
#           #   platform_id: macosx_arm64
#           #   free_threaded_support: True

#     steps:
#       #- name: Set up QEMU
#       #  uses: docker/setup-qemu-action@v3
#       #  with:
#       #    platforms: ppc64le 
#       - name: Checkout scikit-learn
#         uses: actions/checkout@v4

       
#       - name: Install Python 3.11
#         if:  ${{ matrix.platform_id == 'manylinux_ppc64le' }}
#         run: |
#           sudo apt-get update
#           sudo apt-get install -y python3.11 python3.11-dev python3.11-venv
#           sudo update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.11 1
#           python3 --version
          
#       # - name: Setup Python
#       #   uses: actions/setup-python@v5
#       #   with:
#       #     python-version: "3.11" # update once build dependencies are available

#       - uses: conda-incubator/setup-miniconda@v3
#         if: ${{ startsWith(matrix.platform_id, 'macosx') }}

#       - name: Build ppc64le wheel
#         if: ${{ matrix.platform_id == 'manylinux_ppc64le' }}
#         env: 
#           CIBW_CONTAINER_ENGINE: podman
#           CIBW_CONTAINER_PRIVILEGED: true
#           CIBW_BUILD: cp${{ matrix.python }}-${{ matrix.platform_id }}
#           CIBW_MANYLINUX_PPC64LE_IMAGE: quay.io/pypa/manylinux_2_28_ppc64le
#           CIBW_SKIP: "*-musllinux_ppc64le"
#           CIBW_ENVIRONMENT_PASS_LINUX: RUNNER_OS
#           CIBW_BEFORE_BUILD: |
#             yum install -y epel-release gcc gcc-c++ gcc-gfortran git wget pkgconfig cmake openssl-devel && \
#             wget https://ftp2.osuosl.org/pub/ppc64el/openblas/Openblas_0.3.29_ppc64le.tar.gz && \
#             tar -xvpf Openblas_0.3.29_ppc64le.tar.gz -C /usr/local && \
#             export PKG_CONFIG_PATH=$PKG_CONFIG_PATH:/usr/local/lib/pkgconfig && \
#             bash {project}/build_tools/wheels/cibw_before_build.sh {project}
#           CIBW_BEFORE_TEST: |
#             yum install -y epel-release gcc gcc-c++ gcc-gfortran git wget pkgconfig cmake openssl-devel && \
#             pip3 install scipy-openblas64
#             wget https://ftp2.osuosl.org/pub/ppc64el/openblas/Openblas_0.3.29_ppc64le.tar.gz && \
#             tar -xvpf Openblas_0.3.29_ppc64le.tar.gz -C /usr/local && \
#             export PKG_CONFIG_PATH=$PKG_CONFIG_PATH:/usr/local/lib/pkgconfig && \
#             export LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH && \
#             ln -sf /usr/local/lib/libopenblas.so.0 /usr/lib64/libopenblas.so.0 && \
#             bash {project}/build_tools/wheels/cibw_before_test.sh  
#         run: bash build_tools/wheels/build_wheels.sh
#             # sudo apt-get update
#             # sudo apt-get install -y python3.11 python3.11-dev python3.11-venv
#             # sudo update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.11 1
#             # python3 --version 
#             # bash build_tools/wheels/build_wheels.sh
           
#       - name: Build and test wheels
#         if: ${{ matrix.platform_id != 'manylinux_ppc64le' }}
#         env:
#           #CIBW_CONTAINER_ENGINE: podman
#           #CIBW_CONTAINER_PRIVILEGED: true
#           CIBW_PRERELEASE_PYTHONS: ${{ matrix.prerelease_pythons }}
#           CIBW_FREE_THREADED_SUPPORT: ${{ matrix.free_threaded_support }}
#           CIBW_ENVIRONMENT: SKLEARN_SKIP_NETWORK_TESTS=1
#           CIBW_BUILD: cp${{ matrix.python }}-${{ matrix.platform_id }}
#           CIBW_ARCHS: all
#           CIBW_MANYLINUX_X86_64_IMAGE: ${{ matrix.manylinux_image }}
#           CIBW_MANYLINUX_I686_IMAGE: ${{ matrix.manylinux_image }}
#           # Needed on Windows CI to compile with Visual Studio compiler
#           # otherwise Meson detects a MINGW64 platform and use MINGW64
#           # toolchain

#           # CIBW_MANYLINUX_PPC64LE_IMAGE: quay.io/pypa/manylinux_2_28_ppc64le
#           # CIBW_SKIP: "*-musllinux_ppc64le"

#           # CIBW_BEFORE_BUILD: |
#           #   # yum install -y epel-release gcc gcc-c++ gcc-gfortran git wget pkgconfig cmake openssl-devel && \
#           #   # wget https://ftp2.osuosl.org/pub/ppc64el/openblas/Openblas_0.3.29_ppc64le.tar.gz && \
#           #   # tar -xvpf Openblas_0.3.29_ppc64le.tar.gz -C /usr/local && \
#           #   # export PKG_CONFIG_PATH=$PKG_CONFIG_PATH:/usr/local/lib/pkgconfig && \
#           #   # bash {project}/build_tools/wheels/cibw_before_build.sh {project}
#           CIBW_CONFIG_SETTINGS_WINDOWS: "setup-args=--vsenv"
#           CIBW_REPAIR_WHEEL_COMMAND_WINDOWS: bash build_tools/github/repair_windows_wheels.sh {wheel} {dest_dir}
#           CIBW_BEFORE_BUILD: bash {project}/build_tools/wheels/cibw_before_build.sh {project}
#           CIBW_BEFORE_TEST_WINDOWS: bash build_tools/github/build_minimal_windows_image.sh ${{ matrix.python }}
#           # CIBW_BEFORE_TEST: |
#           #   yum install -y epel-release gcc gcc-c++ gcc-gfortran git wget pkgconfig cmake openssl-devel && \
#           #   pip3 install scipy-openblas64
#           #   wget https://ftp2.osuosl.org/pub/ppc64el/openblas/Openblas_0.3.29_ppc64le.tar.gz && \
#           #   tar -xvpf Openblas_0.3.29_ppc64le.tar.gz -C /usr/local && \
#           #   export PKG_CONFIG_PATH=$PKG_CONFIG_PATH:/usr/local/lib/pkgconfig && \
#           #   export LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH && \
#           #   ln -sf /usr/local/lib/libopenblas.so.0 /usr/lib64/libopenblas.so.0 && \
#           #   bash {project}/build_tools/wheels/cibw_before_test.sh
#           CIBW_BEFORE_TEST: bash {project}/build_tools/wheels/cibw_before_test.sh 
#           CIBW_ENVIRONMENT_PASS_LINUX: RUNNER_OS
                      
#           CIBW_TEST_REQUIRES: pytest pandas
           
#           CIBW_TEST_REQUIRES_WINDOWS: ""

#           CIBW_TEST_COMMAND: bash {project}/build_tools/wheels/test_wheels.sh {project}
#           CIBW_TEST_COMMAND_WINDOWS: bash {project}/build_tools/github/test_windows_wheels.sh ${{ matrix.python }} {project}
#           CIBW_BUILD_VERBOSITY: 1

#         run: bash build_tools/wheels/build_wheels.sh

      
#       - name: Store artifacts
#         uses: actions/upload-artifact@v4
#         with:
#           name: cibw-wheels-cp${{ matrix.python }}-${{ matrix.platform_id }}
#           path: wheelhouse/*.whl

#   update-tracker:
#     uses: ./.github/workflows/update_tracking_issue.yml
#     if: ${{ always() }}
#     needs: [build_wheels]
#     with:
#       job_status: ${{ needs.build_wheels.result }}
#     secrets:
#       BOT_GITHUB_TOKEN: ${{ secrets.BOT_GITHUB_TOKEN }}

#   # Build the source distribution under Linux
#   build_sdist:
#     name: Source distribution
#     runs-on: ubuntu-latest
#     needs: check_build_trigger
#     if: needs.check_build_trigger.outputs.build

#     steps:
#       - name: Checkout scikit-learn
#         uses: actions/checkout@v4

#       - name: Setup Python
#         uses: actions/setup-python@v5
#         with:
#           python-version: "3.9" # update once build dependencies are available

#       - name: Build source distribution
#         run: bash build_tools/github/build_source.sh

#       - name: Test source distribution
#         run: bash build_tools/github/test_source.sh
#         env:
#           SKLEARN_SKIP_NETWORK_TESTS: 1

#       - name: Store artifacts
#         uses: actions/upload-artifact@v4
#         with:
#           name: cibw-sdist
#           path: dist/*.tar.gz

#   # Upload the wheels and the source distribution
#   upload_anaconda:
#     name: Upload to Anaconda
#     runs-on: ubuntu-latest
#     environment: upload_anaconda
#     needs: [build_wheels, build_sdist]
#     # The artifacts cannot be uploaded on PRs
#     if: github.event_name != 'pull_request'

#     steps:
#       - name: Checkout scikit-learn
#         uses: actions/checkout@v4

#       - name: Download artifacts
#         uses: actions/download-artifact@v4
#         with:
#           pattern: cibw-*
#           path: dist
#           merge-multiple: true

#       - name: Setup Python
#         uses: actions/setup-python@v5

#       - name: Upload artifacts
#         env:
#           # Secret variables need to be mapped to environment variables explicitly
#           SCIKIT_LEARN_NIGHTLY_UPLOAD_TOKEN: ${{ secrets.SCIKIT_LEARN_NIGHTLY_UPLOAD_TOKEN }}
#           SCIKIT_LEARN_STAGING_UPLOAD_TOKEN: ${{ secrets.SCIKIT_LEARN_STAGING_UPLOAD_TOKEN }}
#           ARTIFACTS_PATH: dist
#         # Force a replacement if the remote file already exists
#         run: bash build_tools/github/upload_anaconda.sh








#===================================================================working finr 10-03-25



# # Workflow to build and test wheels
# name: Wheel builder
# permissions:
#   contents: read

# on:
#   schedule:
#     # Nightly build at 3:42 A.M.
#     - cron: "42 3 */1 * *"
#   push:
#     branches:
#       - main
#       # Release branches
#       - "[0-9]+.[0-9]+.X"
#       - ppc_scikit_learn
#   pull_request:
#     branches:
#       - main
#       - "[0-9]+.[0-9]+.X"
#   # Manual run
#   workflow_dispatch:

# concurrency:
#   group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
#   cancel-in-progress: true

# jobs:
#   # Check whether to build the wheels and the source tarball
#   check_build_trigger:
#     name: Check build trigger
#     runs-on: ubuntu-latest
#     if: github.repository == 'scikit-learn/scikit-learn' || github.repository == 'PankhudiJ17/scikit-learn'
#     outputs:
#       build: ${{ steps.check_build_trigger.outputs.build }}

#     steps:
#       - name: Checkout scikit-learn
#         uses: actions/checkout@v4
#         with:
#           ref: ${{ github.event.pull_request.head.sha }}

#       - id: check_build_trigger
#         name: Check build trigger
#         run: bash build_tools/github/check_build_trigger.sh

#   # Build the wheels for Linux, Windows and macOS for Python 3.9 and newer
#   build_wheels:
#     name: Build wheel for cp${{ matrix.python }}-${{ matrix.platform_id }}-${{ matrix.manylinux_image }}
#     runs-on: linux.ppc64le
#     #${{ matrix.os }}

#     # For conda-incubator/setup-miniconda to work
#     defaults:
#       run:
#         shell: bash -el {0}
#     needs: check_build_trigger
#     if: needs.check_build_trigger.outputs.build

#     strategy:
#       # Ensure that a wheel builder finishes even if another fails
#       fail-fast: false
#       matrix:
#         include:
#           # Window 64 bit
#           # - os: windows-latest
#           #   python: 39
#           #   platform_id: win_amd64
#           # - os: windows-latest
#           #   python: 310
#           #   platform_id: win_amd64
#           # - os: windows-latest
#           #   python: 311
#           #   platform_id: win_amd64
#           # - os: windows-latest
#           #   python: 312
#           #   platform_id: win_amd64
#           # - os: windows-latest
#           #   python: 313
#           #   platform_id: win_amd64
#           # - os: windows-latest
#           #   python: 313t
#           #   platform_id: win_amd64
#           #   free_threaded_support: True

#           # # Linux 64 bit manylinux2014
#           # - os: ubuntu-latest
#           #   python: 39
#           #   platform_id: manylinux_x86_64
#           #   manylinux_image: manylinux2014

#           # # NumPy on Python 3.10 only supports 64bit and is only available with manylinux2014
#           # - os: ubuntu-latest
#           #   python: 310
#           #   platform_id: manylinux_x86_64
#           #   manylinux_image: manylinux2014

#           # - os: ubuntu-latest
#           #   python: 311
#           #   platform_id: manylinux_x86_64
#           #   manylinux_image: manylinux2014
#           # - os: ubuntu-latest
#           #   python: 312
#           #   platform_id: manylinux_x86_64
#           #   manylinux_image: manylinux2014
#           # - os: ubuntu-latest
#           #   python: 313
#           #   platform_id: manylinux_x86_64
#           #   manylinux_image: manylinux2014
#           # - os: ubuntu-latest
#           #   python: 313t
#           #   platform_id: manylinux_x86_64
#           #   manylinux_image: manylinux2014
#           #   free_threaded_support: True

#           # # # Linux 64 bit manylinux2014
#           # - os: ubuntu-24.04-arm
#           #   python: 39
#           #   platform_id: manylinux_aarch64
#           #   manylinux_image: manylinux2014
#           # - os: ubuntu-24.04-arm
#           #   python: 310
#           #   platform_id: manylinux_aarch64
#           #   manylinux_image: manylinux2014
#           # - os: ubuntu-24.04-arm
#           #   python: 311
#           #   platform_id: manylinux_aarch64
#           #   manylinux_image: manylinux2014
#           # - os: ubuntu-24.04-arm
#           #   python: 312
#           #   platform_id: manylinux_aarch64
#           #   manylinux_image: manylinux2014
#           # - os: ubuntu-24.04-arm
#           #   python: 313
#           #   platform_id: manylinux_aarch64
#           #   manylinux_image: manylinux2014

#           # #for pc64le
#           - os: linux.ppc64le #github runner , dnt have for ppc , we use self hosted runner coz we dont hve for ppc
#             python: 39
#             platform_id: manylinux_ppc64le
#             manylinux_image: manylinux_2_28

#           - os: linux.ppc64le
#             python: 310
#             platform_id: manylinux_ppc64le
#             manylinux_image: manylinux_2_28
          
#           - os: linux.ppc64le
#             python: 311
#             platform_id: manylinux_ppc64le
#             manylinux_image: manylinux_2_28

#           - os: linux.ppc64le
#             python: 312
#             platform_id: manylinux_ppc64le
#             manylinux_image: manylinux_2_28

#           - os: linux.ppc64le
#             python: 313
#             platform_id: manylinux_ppc64le
#             manylinux_image: manylinux_2_28


#           # # MacOS x86_64
#           # - os: macos-13
#           #   python: 39
#           #   platform_id: macosx_x86_64
#           # - os: macos-13
#           #   python: 310
#           #   platform_id: macosx_x86_64
#           # - os: macos-13
#           #   python: 311
#           #   platform_id: macosx_x86_64
#           # - os: macos-13
#           #   python: 312
#           #   platform_id: macosx_x86_64
#           # - os: macos-13
#           #   python: 313
#           #   platform_id: macosx_x86_64
#           # - os: macos-13
#           #   python: 313t
#           #   platform_id: macosx_x86_64
#           #   free_threaded_support: True

#           # # MacOS arm64
#           # - os: macos-14
#           #   python: 39
#           #   platform_id: macosx_arm64
#           # - os: macos-14
#           #   python: 310
#           #   platform_id: macosx_arm64
#           # - os: macos-14
#           #   python: 311
#           #   platform_id: macosx_arm64
#           # - os: macos-14
#           #   python: 312
#           #   platform_id: macosx_arm64
#           # - os: macos-14
#           #   python: 313
#           #   platform_id: macosx_arm64
#           # - os: macos-14
#           #   python: 313t
#           #   platform_id: macosx_arm64
#           #   free_threaded_support: True

#     steps:
#       #- name: Set up QEMU
#       #  uses: docker/setup-qemu-action@v3
#       #  with:
#       #    platforms: ppc64le 
#       - name: Checkout scikit-learn
#         uses: actions/checkout@v4


#       - name: Install Python 3.11
#         run: |
#           sudo apt-get update
#           sudo apt-get install -y python3.11 python3.11-dev python3.11-venv
#           sudo update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.11 1
#           python3 --version
          

#       # - name: Setup Python
#       #   uses: actions/setup-python@v5
#       #   with:
#       #     python-version: "3.11" # update once build dependencies are available

#       - uses: conda-incubator/setup-miniconda@v3
#         if: ${{ startsWith(matrix.platform_id, 'macosx') }}

#       - name: Build and test wheels
#         env:
#           CIBW_CONTAINER_ENGINE: podman
#           CIBW_CONTAINER_PRIVILEGED: true
#           CIBW_PRERELEASE_PYTHONS: ${{ matrix.prerelease_pythons }}
#           CIBW_FREE_THREADED_SUPPORT: ${{ matrix.free_threaded_support }}
#           CIBW_ENVIRONMENT: SKLEARN_SKIP_NETWORK_TESTS=1
#           CIBW_BUILD: cp${{ matrix.python }}-${{ matrix.platform_id }}
#           CIBW_ARCHS: all
#           CIBW_MANYLINUX_X86_64_IMAGE: ${{ matrix.manylinux_image }}
#           CIBW_MANYLINUX_I686_IMAGE: ${{ matrix.manylinux_image }}
#           # Needed on Windows CI to compile with Visual Studio compiler
#           # otherwise Meson detects a MINGW64 platform and use MINGW64
#           # toolchain

#           CIBW_MANYLINUX_PPC64LE_IMAGE: quay.io/pypa/manylinux_2_28_ppc64le
#           CIBW_SKIP: "*-musllinux_ppc64le"
#           #CIBW_BEFORE_BUILD: "yum install -y epel-release gcc gcc-c++ gcc-gfortran git wget pkgconfig cmake && wget https://ftp2.osuosl.org/pub/ppc64el/openblas/Openblas_0.3.29_ppc64le.tar.gz && tar -xvpf Openblas_0.3.29_ppc64le.tar.gz -C /usr/local && export PKG_CONFIG_PATH=$PKG_CONFIG_PATH:/usr/local/lib/pkgconfig"
#           CIBW_BEFORE_BUILD: |
#             yum install -y epel-release gcc gcc-c++ gcc-gfortran git wget pkgconfig cmake openssl-devel && \
#             wget https://ftp2.osuosl.org/pub/ppc64el/openblas/Openblas_0.3.29_ppc64le.tar.gz && \
#             tar -xvpf Openblas_0.3.29_ppc64le.tar.gz -C /usr/local && \
#             export PKG_CONFIG_PATH=$PKG_CONFIG_PATH:/usr/local/lib/pkgconfig && \
#             bash {project}/build_tools/wheels/cibw_before_build.sh {project}

#           CIBW_CONFIG_SETTINGS_WINDOWS: "setup-args=--vsenv"
#           CIBW_REPAIR_WHEEL_COMMAND_WINDOWS: bash build_tools/github/repair_windows_wheels.sh {wheel} {dest_dir}
#           #CIBW_BEFORE_BUILD: bash {project}/build_tools/wheels/cibw_before_build.sh {project}
#           CIBW_BEFORE_TEST_WINDOWS: bash build_tools/github/build_minimal_windows_image.sh ${{ matrix.python }}
#           CIBW_BEFORE_TEST: |
#             yum install -y epel-release gcc gcc-c++ gcc-gfortran git wget pkgconfig cmake openssl-devel && \
#             pip3 install scipy-openblas64
#             wget https://ftp2.osuosl.org/pub/ppc64el/openblas/Openblas_0.3.29_ppc64le.tar.gz && \
#             tar -xvpf Openblas_0.3.29_ppc64le.tar.gz -C /usr/local && \
#            # export LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH
#            # export PKG_CONFIG_PATH=$PKG_CONFIG_PATH:/usr/local/lib/pkgconfig && \
#             # bash {project}/build_tools/wheels/cibw_before_test.sh && \

#             export PKG_CONFIG_PATH=$PKG_CONFIG_PATH:/usr/local/lib/pkgconfig && \
#             export LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH && \
#            # ln -sf /usr/local/lib/libopenblas.so.0 /usr/lib64/libopenblas.so.0 && \
#            # echo "before cibw_before_test.sh file"
#             bash {project}/build_tools/wheels/cibw_before_test.sh
#            # echo "Finish"
#           CIBW_ENVIRONMENT_PASS_LINUX: RUNNER_OS
#            # echo "Before Runner_OS"
            
#             #echo "After Runner_OS"

            
#           CIBW_TEST_REQUIRES: pytest pandas
#             #echo "Before installing pytest_pandas"
#             # pytest pandas
#             #echo "installing after pytest_pandas"
#           # On Windows, we use a custom Docker image and CIBW_TEST_REQUIRES_WINDOWS
#           # does not make sense because it would install dependencies in the host
#           # rather than inside the Docker image
#           CIBW_TEST_REQUIRES_WINDOWS: ""

#           CIBW_TEST_COMMAND: |
#            echo "before test_wheel.sh"
#            bash {project}/build_tools/wheels/test_wheels.sh {project}
#            echo "After test_wheel.sh" 
#           CIBW_TEST_COMMAND_WINDOWS: bash {project}/build_tools/github/test_windows_wheels.sh ${{ matrix.python }} {project}
#           CIBW_BUILD_VERBOSITY: 1

#         run: bash build_tools/wheels/build_wheels.sh

#       - name: openblas
#         run: |
#           sudo find / -name *openblas*

#       - name: Store artifacts
#         uses: actions/upload-artifact@v4
#         with:
#           name: cibw-wheels-cp${{ matrix.python }}-${{ matrix.platform_id }}
#           path: wheelhouse/*.whl

#   update-tracker:
#     uses: ./.github/workflows/update_tracking_issue.yml
#     if: ${{ always() }}
#     needs: [build_wheels]
#     with:
#       job_status: ${{ needs.build_wheels.result }}
#     secrets:
#       BOT_GITHUB_TOKEN: ${{ secrets.BOT_GITHUB_TOKEN }}

#   # Build the source distribution under Linux
#   build_sdist:
#     name: Source distribution
#     runs-on: ubuntu-latest
#     needs: check_build_trigger
#     if: needs.check_build_trigger.outputs.build

#     steps:
#       - name: Checkout scikit-learn
#         uses: actions/checkout@v4

#       - name: Setup Python
#         uses: actions/setup-python@v5
#         with:
#           python-version: "3.9" # update once build dependencies are available

#       - name: Build source distribution
#         run: bash build_tools/github/build_source.sh

#       - name: Test source distribution
#         run: bash build_tools/github/test_source.sh
#         env:
#           SKLEARN_SKIP_NETWORK_TESTS: 1

#       - name: Store artifacts
#         uses: actions/upload-artifact@v4
#         with:
#           name: cibw-sdist
#           path: dist/*.tar.gz

#   # Upload the wheels and the source distribution
#   upload_anaconda:
#     name: Upload to Anaconda
#     runs-on: ubuntu-latest
#     environment: upload_anaconda
#     needs: [build_wheels, build_sdist]
#     # The artifacts cannot be uploaded on PRs
#     if: github.event_name != 'pull_request'

#     steps:
#       - name: Checkout scikit-learn
#         uses: actions/checkout@v4

#       - name: Download artifacts
#         uses: actions/download-artifact@v4
#         with:
#           pattern: cibw-*
#           path: dist
#           merge-multiple: true

#       - name: Setup Python
#         uses: actions/setup-python@v5

#       - name: Upload artifacts
#         env:
#           # Secret variables need to be mapped to environment variables explicitly
#           SCIKIT_LEARN_NIGHTLY_UPLOAD_TOKEN: ${{ secrets.SCIKIT_LEARN_NIGHTLY_UPLOAD_TOKEN }}
#           SCIKIT_LEARN_STAGING_UPLOAD_TOKEN: ${{ secrets.SCIKIT_LEARN_STAGING_UPLOAD_TOKEN }}
#           ARTIFACTS_PATH: dist
#         # Force a replacement if the remote file already exists
#         run: bash build_tools/github/upload_anaconda.sh










# # Workflow to build and test wheels
# name: Wheel builder
# permissions:
#   contents: read

# on:
#   schedule:
#     # Nightly build at 3:42 A.M.
#     - cron: "42 3 */1 * *"
#   push:
#     branches:
#       - main
#       # Release branches
#       - "[0-9]+.[0-9]+.X"
#       - ppc_scikit_learn
#   pull_request:
#     branches:
#       - main
#       - "[0-9]+.[0-9]+.X"
#   # Manual run
#   workflow_dispatch:

# concurrency:
#   group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
#   cancel-in-progress: true

# jobs:
#   # Check whether to build the wheels and the source tarball
#   check_build_trigger:
#     name: Check build trigger
#     runs-on: ubuntu-latest
#     if: github.repository == 'scikit-learn/scikit-learn' || github.repository == 'PankhudiJ17/scikit-learn'
#     outputs:
#       build: ${{ steps.check_build_trigger.outputs.build }}

#     steps:
#       - name: Checkout scikit-learn
#         uses: actions/checkout@v4
#         with:
#           ref: ${{ github.event.pull_request.head.sha }}

#       - id: check_build_trigger
#         name: Check build trigger
#         run: bash build_tools/github/check_build_trigger.sh

#   # Build the wheels for Linux, Windows and macOS for Python 3.9 and newer
#   build_wheels:
#     name: Build wheel for cp${{ matrix.python }}-${{ matrix.platform_id }}-${{ matrix.manylinux_image }}
#     runs-on: linux.ppc64le
#     #${{ matrix.os }}

#     # For conda-incubator/setup-miniconda to work
#     defaults:
#       run:
#         shell: bash -el {0}
#     needs: check_build_trigger
#     if: needs.check_build_trigger.outputs.build

#     strategy:
#       # Ensure that a wheel builder finishes even if another fails
#       fail-fast: false
#       matrix:
#         include:
#           # Window 64 bit
#           # - os: windows-latest
#           #   python: 39
#           #   platform_id: win_amd64
#           # - os: windows-latest
#           #   python: 310
#           #   platform_id: win_amd64
#           # - os: windows-latest
#           #   python: 311
#           #   platform_id: win_amd64
#           # - os: windows-latest
#           #   python: 312
#           #   platform_id: win_amd64
#           # - os: windows-latest
#           #   python: 313
#           #   platform_id: win_amd64
#           # - os: windows-latest
#           #   python: 313t
#           #   platform_id: win_amd64
#           #   free_threaded_support: True

#           # # Linux 64 bit manylinux2014
#           # - os: ubuntu-latest
#           #   python: 39
#           #   platform_id: manylinux_x86_64
#           #   manylinux_image: manylinux2014

#           # # NumPy on Python 3.10 only supports 64bit and is only available with manylinux2014
#           # - os: ubuntu-latest
#           #   python: 310
#           #   platform_id: manylinux_x86_64
#           #   manylinux_image: manylinux2014

#           # - os: ubuntu-latest
#           #   python: 311
#           #   platform_id: manylinux_x86_64
#           #   manylinux_image: manylinux2014
#           # - os: ubuntu-latest
#           #   python: 312
#           #   platform_id: manylinux_x86_64
#           #   manylinux_image: manylinux2014
#           # - os: ubuntu-latest
#           #   python: 313
#           #   platform_id: manylinux_x86_64
#           #   manylinux_image: manylinux2014
#           # - os: ubuntu-latest
#           #   python: 313t
#           #   platform_id: manylinux_x86_64
#           #   manylinux_image: manylinux2014
#           #   free_threaded_support: True

#           # # # Linux 64 bit manylinux2014
#           # - os: ubuntu-24.04-arm
#           #   python: 39
#           #   platform_id: manylinux_aarch64
#           #   manylinux_image: manylinux2014
#           # - os: ubuntu-24.04-arm
#           #   python: 310
#           #   platform_id: manylinux_aarch64
#           #   manylinux_image: manylinux2014
#           # - os: ubuntu-24.04-arm
#           #   python: 311
#           #   platform_id: manylinux_aarch64
#           #   manylinux_image: manylinux2014
#           # - os: ubuntu-24.04-arm
#           #   python: 312
#           #   platform_id: manylinux_aarch64
#           #   manylinux_image: manylinux2014
#           # - os: ubuntu-24.04-arm
#           #   python: 313
#           #   platform_id: manylinux_aarch64
#           #   manylinux_image: manylinux2014

#           # #for pc64le
#           - os: linux.ppc64le #github runner , dnt have for ppc , we use self hosted runner coz we dont hve for ppc
#             python: 39
#             platform_id: manylinux_ppc64le
#             manylinux_image: manylinux_2_28

#           - os: linux.ppc64le
#             python: 310
#             platform_id: manylinux_ppc64le
#             manylinux_image: manylinux_2_28
          
#           - os: linux.ppc64le
#             python: 311
#             platform_id: manylinux_ppc64le
#             manylinux_image: manylinux_2_28

#           - os: linux.ppc64le
#             python: 312
#             platform_id: manylinux_ppc64le
#             manylinux_image: manylinux_2_28

#           - os: linux.ppc64le
#             python: 313
#             platform_id: manylinux_ppc64le
#             manylinux_image: manylinux_2_28


#           # # MacOS x86_64
#           # - os: macos-13
#           #   python: 39
#           #   platform_id: macosx_x86_64
#           # - os: macos-13
#           #   python: 310
#           #   platform_id: macosx_x86_64
#           # - os: macos-13
#           #   python: 311
#           #   platform_id: macosx_x86_64
#           # - os: macos-13
#           #   python: 312
#           #   platform_id: macosx_x86_64
#           # - os: macos-13
#           #   python: 313
#           #   platform_id: macosx_x86_64
#           # - os: macos-13
#           #   python: 313t
#           #   platform_id: macosx_x86_64
#           #   free_threaded_support: True

#           # # MacOS arm64
#           # - os: macos-14
#           #   python: 39
#           #   platform_id: macosx_arm64
#           # - os: macos-14
#           #   python: 310
#           #   platform_id: macosx_arm64
#           # - os: macos-14
#           #   python: 311
#           #   platform_id: macosx_arm64
#           # - os: macos-14
#           #   python: 312
#           #   platform_id: macosx_arm64
#           # - os: macos-14
#           #   python: 313
#           #   platform_id: macosx_arm64
#           # - os: macos-14
#           #   python: 313t
#           #   platform_id: macosx_arm64
#           #   free_threaded_support: True

#     steps:
#       #- name: Set up QEMU
#       #  uses: docker/setup-qemu-action@v3
#       #  with:
#       #    platforms: ppc64le 
#       - name: Checkout scikit-learn
#         uses: actions/checkout@v4


#       - name: Install Python 3.11
#         run: |
#           sudo apt-get update
#           sudo apt-get install -y python3.11 python3.11-dev python3.11-venv
#           sudo update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.11 1
#           python3 --version
          

#       # - name: Setup Python
#       #   uses: actions/setup-python@v5
#       #   with:
#       #     python-version: "3.11" # update once build dependencies are available

#       - uses: conda-incubator/setup-miniconda@v3
#         if: ${{ startsWith(matrix.platform_id, 'macosx') }}

#       - name: Build and test wheels
#         env:
#           CIBW_CONTAINER_ENGINE: podman
#           CIBW_CONTAINER_PRIVILEGED: true
#           CIBW_PRERELEASE_PYTHONS: ${{ matrix.prerelease_pythons }}
#           CIBW_FREE_THREADED_SUPPORT: ${{ matrix.free_threaded_support }}
#           CIBW_ENVIRONMENT: SKLEARN_SKIP_NETWORK_TESTS=1
#           CIBW_BUILD: cp${{ matrix.python }}-${{ matrix.platform_id }}
#           CIBW_ARCHS: all
#           CIBW_MANYLINUX_X86_64_IMAGE: ${{ matrix.manylinux_image }}
#           CIBW_MANYLINUX_I686_IMAGE: ${{ matrix.manylinux_image }}
#           # Needed on Windows CI to compile with Visual Studio compiler
#           # otherwise Meson detects a MINGW64 platform and use MINGW64
#           # toolchain

#           CIBW_MANYLINUX_PPC64LE_IMAGE: quay.io/pypa/manylinux_2_28_ppc64le
#           CIBW_SKIP: "*-musllinux_ppc64le"
#           #CIBW_BEFORE_BUILD: "yum install -y epel-release gcc gcc-c++ gcc-gfortran git wget pkgconfig cmake && wget https://ftp2.osuosl.org/pub/ppc64el/openblas/Openblas_0.3.29_ppc64le.tar.gz && tar -xvpf Openblas_0.3.29_ppc64le.tar.gz -C /usr/local && export PKG_CONFIG_PATH=$PKG_CONFIG_PATH:/usr/local/lib/pkgconfig"
#           CIBW_BEFORE_BUILD: |
#             yum install -y epel-release gcc gcc-c++ gcc-gfortran git wget pkgconfig cmake openssl-devel && \
#             wget https://ftp2.osuosl.org/pub/ppc64el/openblas/Openblas_0.3.29_ppc64le.tar.gz && \
#             tar -xvpf Openblas_0.3.29_ppc64le.tar.gz -C /usr/local && \
#             export PKG_CONFIG_PATH=$PKG_CONFIG_PATH:/usr/local/lib/pkgconfig && \
#             bash {project}/build_tools/wheels/cibw_before_build.sh {project}

#           CIBW_CONFIG_SETTINGS_WINDOWS: "setup-args=--vsenv"
#           CIBW_REPAIR_WHEEL_COMMAND_WINDOWS: bash build_tools/github/repair_windows_wheels.sh {wheel} {dest_dir}
#           #CIBW_BEFORE_BUILD: bash {project}/build_tools/wheels/cibw_before_build.sh {project}
#           CIBW_BEFORE_TEST_WINDOWS: bash build_tools/github/build_minimal_windows_image.sh ${{ matrix.python }}
#           CIBW_BEFORE_TEST: |
#             yum install -y epel-release gcc gcc-c++ gcc-gfortran git wget pkgconfig cmake openssl-devel && \
#             pip3 install scipy-openblas64
#             wget https://ftp2.osuosl.org/pub/ppc64el/openblas/Openblas_0.3.29_ppc64le.tar.gz && \
#             tar -xvpf Openblas_0.3.29_ppc64le.tar.gz -C /usr/local && \
#            # export LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH
#            # export PKG_CONFIG_PATH=$PKG_CONFIG_PATH:/usr/local/lib/pkgconfig && \
#             # bash {project}/build_tools/wheels/cibw_before_test.sh && \

#             export PKG_CONFIG_PATH=$PKG_CONFIG_PATH:/usr/local/lib/pkgconfig && \
#             export LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH && \
#            # ln -sf /usr/local/lib/libopenblas.so.0 /usr/lib64/libopenblas.so.0 && \
#            # echo "before cibw_before_test.sh file"
#             bash {project}/build_tools/wheels/cibw_before_test.sh
#            # echo "Finish"
#           CIBW_ENVIRONMENT_PASS_LINUX: RUNNER_OS
#            # echo "Before Runner_OS"
            
#             #echo "After Runner_OS"

            
#           CIBW_TEST_REQUIRES: pytest pandas
#             #echo "Before installing pytest_pandas"
#             # pytest pandas
#             #echo "installing after pytest_pandas"
#           # On Windows, we use a custom Docker image and CIBW_TEST_REQUIRES_WINDOWS
#           # does not make sense because it would install dependencies in the host
#           # rather than inside the Docker image
#           CIBW_TEST_REQUIRES_WINDOWS: ""

#           CIBW_TEST_COMMAND: |
#            echo "before test_wheel.sh"
#            bash {project}/build_tools/wheels/test_wheels.sh {project}
#            echo "After test_wheel.sh" 
#           CIBW_TEST_COMMAND_WINDOWS: bash {project}/build_tools/github/test_windows_wheels.sh ${{ matrix.python }} {project}
#           CIBW_BUILD_VERBOSITY: 1

#         run: bash build_tools/wheels/build_wheels.sh

#       - name: openblas
#         run: |
#           sudo find / -name *openblas*

#       - name: Store artifacts
#         uses: actions/upload-artifact@v4
#         with:
#           name: cibw-wheels-cp${{ matrix.python }}-${{ matrix.platform_id }}
#           path: wheelhouse/*.whl

#   update-tracker:
#     uses: ./.github/workflows/update_tracking_issue.yml
#     if: ${{ always() }}
#     needs: [build_wheels]
#     with:
#       job_status: ${{ needs.build_wheels.result }}
#     secrets:
#       BOT_GITHUB_TOKEN: ${{ secrets.BOT_GITHUB_TOKEN }}

#   # Build the source distribution under Linux
#   build_sdist:
#     name: Source distribution
#     runs-on: ubuntu-latest
#     needs: check_build_trigger
#     if: needs.check_build_trigger.outputs.build

#     steps:
#       - name: Checkout scikit-learn
#         uses: actions/checkout@v4

#       - name: Setup Python
#         uses: actions/setup-python@v5
#         with:
#           python-version: "3.9" # update once build dependencies are available

#       - name: Build source distribution
#         run: bash build_tools/github/build_source.sh

#       - name: Test source distribution
#         run: bash build_tools/github/test_source.sh
#         env:
#           SKLEARN_SKIP_NETWORK_TESTS: 1

#       - name: Store artifacts
#         uses: actions/upload-artifact@v4
#         with:
#           name: cibw-sdist
#           path: dist/*.tar.gz

#   # Upload the wheels and the source distribution
#   upload_anaconda:
#     name: Upload to Anaconda
#     runs-on: ubuntu-latest
#     environment: upload_anaconda
#     needs: [build_wheels, build_sdist]
#     # The artifacts cannot be uploaded on PRs
#     if: github.event_name != 'pull_request'

#     steps:
#       - name: Checkout scikit-learn
#         uses: actions/checkout@v4

#       - name: Download artifacts
#         uses: actions/download-artifact@v4
#         with:
#           pattern: cibw-*
#           path: dist
#           merge-multiple: true

#       - name: Setup Python
#         uses: actions/setup-python@v5

#       - name: Upload artifacts
#         env:
#           # Secret variables need to be mapped to environment variables explicitly
#           SCIKIT_LEARN_NIGHTLY_UPLOAD_TOKEN: ${{ secrets.SCIKIT_LEARN_NIGHTLY_UPLOAD_TOKEN }}
#           SCIKIT_LEARN_STAGING_UPLOAD_TOKEN: ${{ secrets.SCIKIT_LEARN_STAGING_UPLOAD_TOKEN }}
#           ARTIFACTS_PATH: dist
#         # Force a replacement if the remote file already exists
#         run: bash build_tools/github/upload_anaconda.sh










# # Workflow to build and test wheels
# name: Wheel builder
# permissions:
#   contents: read

# on:
#   schedule:
#     # Nightly build at 3:42 A.M.
#     - cron: "42 3 */1 * *"
#   push:
#     branches:
#       - main
#       # Release branches
#       - "[0-9]+.[0-9]+.X"
#       - ppc_scikit_learn
#   pull_request:
#     branches:
#       - main
#       - "[0-9]+.[0-9]+.X"
#   # Manual run
#   workflow_dispatch:

# concurrency:
#   group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
#   cancel-in-progress: true

# jobs:
#   # Check whether to build the wheels and the source tarball
#   check_build_trigger:
#     name: Check build trigger
#     runs-on: ubuntu-latest
#     if: github.repository == 'scikit-learn/scikit-learn' || github.repository == 'PankhudiJ17/scikit-learn'
#     outputs:
#       build: ${{ steps.check_build_trigger.outputs.build }}

#     steps:
#       - name: Checkout scikit-learn
#         uses: actions/checkout@v4
#         with:
#           ref: ${{ github.event.pull_request.head.sha }}

#       - id: check_build_trigger
#         name: Check build trigger
#         run: bash build_tools/github/check_build_trigger.sh

#   # Build the wheels for Linux, Windows and macOS for Python 3.9 and newer
#   build_wheels:
#     name: Build wheel for cp${{ matrix.python }}-${{ matrix.platform_id }}-${{ matrix.manylinux_image }}
#     runs-on: linux.ppc64le
#     #${{ matrix.os }}

#     # For conda-incubator/setup-miniconda to work
#     defaults:
#       run:
#         shell: bash -el {0}
#     needs: check_build_trigger
#     if: needs.check_build_trigger.outputs.build

#     strategy:
#       # Ensure that a wheel builder finishes even if another fails
#       fail-fast: false
#       matrix:
#         include:
#           # Window 64 bit
#           # - os: windows-latest
#           #   python: 39
#           #   platform_id: win_amd64
#           # - os: windows-latest
#           #   python: 310
#           #   platform_id: win_amd64
#           # - os: windows-latest
#           #   python: 311
#           #   platform_id: win_amd64
#           # - os: windows-latest
#           #   python: 312
#           #   platform_id: win_amd64
#           # - os: windows-latest
#           #   python: 313
#           #   platform_id: win_amd64
#           # - os: windows-latest
#           #   python: 313t
#           #   platform_id: win_amd64
#           #   free_threaded_support: True

#           # # Linux 64 bit manylinux2014
#           # - os: ubuntu-latest
#           #   python: 39
#           #   platform_id: manylinux_x86_64
#           #   manylinux_image: manylinux2014

#           # # NumPy on Python 3.10 only supports 64bit and is only available with manylinux2014
#           # - os: ubuntu-latest
#           #   python: 310
#           #   platform_id: manylinux_x86_64
#           #   manylinux_image: manylinux2014

#           # - os: ubuntu-latest
#           #   python: 311
#           #   platform_id: manylinux_x86_64
#           #   manylinux_image: manylinux2014
#           # - os: ubuntu-latest
#           #   python: 312
#           #   platform_id: manylinux_x86_64
#           #   manylinux_image: manylinux2014
#           # - os: ubuntu-latest
#           #   python: 313
#           #   platform_id: manylinux_x86_64
#           #   manylinux_image: manylinux2014
#           # - os: ubuntu-latest
#           #   python: 313t
#           #   platform_id: manylinux_x86_64
#           #   manylinux_image: manylinux2014
#           #   free_threaded_support: True

#           # # # Linux 64 bit manylinux2014
#           # - os: ubuntu-24.04-arm
#           #   python: 39
#           #   platform_id: manylinux_aarch64
#           #   manylinux_image: manylinux2014
#           # - os: ubuntu-24.04-arm
#           #   python: 310
#           #   platform_id: manylinux_aarch64
#           #   manylinux_image: manylinux2014
#           # - os: ubuntu-24.04-arm
#           #   python: 311
#           #   platform_id: manylinux_aarch64
#           #   manylinux_image: manylinux2014
#           # - os: ubuntu-24.04-arm
#           #   python: 312
#           #   platform_id: manylinux_aarch64
#           #   manylinux_image: manylinux2014
#           # - os: ubuntu-24.04-arm
#           #   python: 313
#           #   platform_id: manylinux_aarch64
#           #   manylinux_image: manylinux2014

#           # #for pc64le
#           - os: linux.ppc64le #github runner , dnt have for ppc , we use self hosted runner coz we dont hve for ppc
#             python: 39
#             platform_id: manylinux_ppc64le
#             manylinux_image: manylinux_2_28

#           - os: linux.ppc64le
#             python: 310
#             platform_id: manylinux_ppc64le
#             manylinux_image: manylinux_2_28
          
#           - os: linux.ppc64le
#             python: 311
#             platform_id: manylinux_ppc64le
#             manylinux_image: manylinux_2_28

#           - os: linux.ppc64le
#             python: 312
#             platform_id: manylinux_ppc64le
#             manylinux_image: manylinux_2_28

#           - os: linux.ppc64le
#             python: 313
#             platform_id: manylinux_ppc64le
#             manylinux_image: manylinux_2_28


#           # # MacOS x86_64
#           # - os: macos-13
#           #   python: 39
#           #   platform_id: macosx_x86_64
#           # - os: macos-13
#           #   python: 310
#           #   platform_id: macosx_x86_64
#           # - os: macos-13
#           #   python: 311
#           #   platform_id: macosx_x86_64
#           # - os: macos-13
#           #   python: 312
#           #   platform_id: macosx_x86_64
#           # - os: macos-13
#           #   python: 313
#           #   platform_id: macosx_x86_64
#           # - os: macos-13
#           #   python: 313t
#           #   platform_id: macosx_x86_64
#           #   free_threaded_support: True

#           # # MacOS arm64
#           # - os: macos-14
#           #   python: 39
#           #   platform_id: macosx_arm64
#           # - os: macos-14
#           #   python: 310
#           #   platform_id: macosx_arm64
#           # - os: macos-14
#           #   python: 311
#           #   platform_id: macosx_arm64
#           # - os: macos-14
#           #   python: 312
#           #   platform_id: macosx_arm64
#           # - os: macos-14
#           #   python: 313
#           #   platform_id: macosx_arm64
#           # - os: macos-14
#           #   python: 313t
#           #   platform_id: macosx_arm64
#           #   free_threaded_support: True

#     steps:
#       #- name: Set up QEMU
#       #  uses: docker/setup-qemu-action@v3
#       #  with:
#       #    platforms: ppc64le 
#       - name: Checkout scikit-learn
#         uses: actions/checkout@v4


#       - name: Install Python 3.11
#         run: |
#           sudo apt-get update
#           sudo apt-get install -y python3.11 python3.11-dev python3.11-venv
#           sudo update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.11 1
#           python3 --version
          

#       # - name: Setup Python
#       #   uses: actions/setup-python@v5
#       #   with:
#       #     python-version: "3.11" # update once build dependencies are available

#       - uses: conda-incubator/setup-miniconda@v3
#         if: ${{ startsWith(matrix.platform_id, 'macosx') }}

#       - name: Build and test wheels
#         env:
#           CIBW_CONTAINER_ENGINE: podman
#           CIBW_CONTAINER_PRIVILEGED: true
#           CIBW_PRERELEASE_PYTHONS: ${{ matrix.prerelease_pythons }}
#           CIBW_FREE_THREADED_SUPPORT: ${{ matrix.free_threaded_support }}
#           CIBW_ENVIRONMENT: SKLEARN_SKIP_NETWORK_TESTS=1
#           CIBW_BUILD: cp${{ matrix.python }}-${{ matrix.platform_id }}
#           CIBW_ARCHS: all
#           CIBW_MANYLINUX_X86_64_IMAGE: ${{ matrix.manylinux_image }}
#           CIBW_MANYLINUX_I686_IMAGE: ${{ matrix.manylinux_image }}
#           # Needed on Windows CI to compile with Visual Studio compiler
#           # otherwise Meson detects a MINGW64 platform and use MINGW64
#           # toolchain

#           CIBW_MANYLINUX_PPC64LE_IMAGE: quay.io/pypa/manylinux_2_28_ppc64le
#           CIBW_SKIP: "*-musllinux_ppc64le"
#           #CIBW_BEFORE_BUILD: "yum install -y epel-release gcc gcc-c++ gcc-gfortran git wget pkgconfig cmake && wget https://ftp2.osuosl.org/pub/ppc64el/openblas/Openblas_0.3.29_ppc64le.tar.gz && tar -xvpf Openblas_0.3.29_ppc64le.tar.gz -C /usr/local && export PKG_CONFIG_PATH=$PKG_CONFIG_PATH:/usr/local/lib/pkgconfig"
#           CIBW_BEFORE_BUILD: |
#             yum install -y epel-release gcc gcc-c++ gcc-gfortran git wget pkgconfig cmake openssl-devel && \
#             wget https://ftp2.osuosl.org/pub/ppc64el/openblas/Openblas_0.3.29_ppc64le.tar.gz && \
#             tar -xvpf Openblas_0.3.29_ppc64le.tar.gz -C /usr/local && \
#             export PKG_CONFIG_PATH=$PKG_CONFIG_PATH:/usr/local/lib/pkgconfig && \
#             bash {project}/build_tools/wheels/cibw_before_build.sh {project}

#           CIBW_CONFIG_SETTINGS_WINDOWS: "setup-args=--vsenv"
#           CIBW_REPAIR_WHEEL_COMMAND_WINDOWS: bash build_tools/github/repair_windows_wheels.sh {wheel} {dest_dir}
#           #CIBW_BEFORE_BUILD: bash {project}/build_tools/wheels/cibw_before_build.sh {project}
#           CIBW_BEFORE_TEST_WINDOWS: bash build_tools/github/build_minimal_windows_image.sh ${{ matrix.python }}
#           CIBW_BEFORE_TEST: |
#             yum install -y epel-release gcc gcc-c++ gcc-gfortran git wget pkgconfig cmake openssl-devel && \
#             pip3 install scipy-openblas64
#             wget https://ftp2.osuosl.org/pub/ppc64el/openblas/Openblas_0.3.29_ppc64le.tar.gz && \
#             tar -xvpf Openblas_0.3.29_ppc64le.tar.gz -C /usr/local && \
#            # export LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH
#            # export PKG_CONFIG_PATH=$PKG_CONFIG_PATH:/usr/local/lib/pkgconfig && \
#             # bash {project}/build_tools/wheels/cibw_before_test.sh && \

#             export PKG_CONFIG_PATH=$PKG_CONFIG_PATH:/usr/local/lib/pkgconfig && \
#             export LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH && \
#            # ln -sf /usr/local/lib/libopenblas.so.0 /usr/lib64/libopenblas.so.0 && \
#            # echo "before cibw_before_test.sh file"
#             bash {project}/build_tools/wheels/cibw_before_test.sh
#            # echo "Finish"
#           CIBW_ENVIRONMENT_PASS_LINUX: RUNNER_OS
#            # echo "Before Runner_OS"
            
#             #echo "After Runner_OS"

            
#           CIBW_TEST_REQUIRES: pytest pandas
#             #echo "Before installing pytest_pandas"
#             # pytest pandas
#             #echo "installing after pytest_pandas"
#           # On Windows, we use a custom Docker image and CIBW_TEST_REQUIRES_WINDOWS
#           # does not make sense because it would install dependencies in the host
#           # rather than inside the Docker image
#           CIBW_TEST_REQUIRES_WINDOWS: ""

#           CIBW_TEST_COMMAND: |
#            echo "before test_wheel.sh"
#            bash {project}/build_tools/wheels/test_wheels.sh {project}
#            echo "After test_wheel.sh" 
#           CIBW_TEST_COMMAND_WINDOWS: bash {project}/build_tools/github/test_windows_wheels.sh ${{ matrix.python }} {project}
#           CIBW_BUILD_VERBOSITY: 1

#         run: bash build_tools/wheels/build_wheels.sh

#       - name: openblas
#         run: |
#           sudo find / -name *openblas*

#       - name: Store artifacts
#         uses: actions/upload-artifact@v4
#         with:
#           name: cibw-wheels-cp${{ matrix.python }}-${{ matrix.platform_id }}
#           path: wheelhouse/*.whl

#   update-tracker:
#     uses: ./.github/workflows/update_tracking_issue.yml
#     if: ${{ always() }}
#     needs: [build_wheels]
#     with:
#       job_status: ${{ needs.build_wheels.result }}
#     secrets:
#       BOT_GITHUB_TOKEN: ${{ secrets.BOT_GITHUB_TOKEN }}

#   # Build the source distribution under Linux
#   build_sdist:
#     name: Source distribution
#     runs-on: ubuntu-latest
#     needs: check_build_trigger
#     if: needs.check_build_trigger.outputs.build

#     steps:
#       - name: Checkout scikit-learn
#         uses: actions/checkout@v4

#       - name: Setup Python
#         uses: actions/setup-python@v5
#         with:
#           python-version: "3.9" # update once build dependencies are available

#       - name: Build source distribution
#         run: bash build_tools/github/build_source.sh

#       - name: Test source distribution
#         run: bash build_tools/github/test_source.sh
#         env:
#           SKLEARN_SKIP_NETWORK_TESTS: 1

#       - name: Store artifacts
#         uses: actions/upload-artifact@v4
#         with:
#           name: cibw-sdist
#           path: dist/*.tar.gz

#   # Upload the wheels and the source distribution
#   upload_anaconda:
#     name: Upload to Anaconda
#     runs-on: ubuntu-latest
#     environment: upload_anaconda
#     needs: [build_wheels, build_sdist]
#     # The artifacts cannot be uploaded on PRs
#     if: github.event_name != 'pull_request'

#     steps:
#       - name: Checkout scikit-learn
#         uses: actions/checkout@v4

#       - name: Download artifacts
#         uses: actions/download-artifact@v4
#         with:
#           pattern: cibw-*
#           path: dist
#           merge-multiple: true

#       - name: Setup Python
#         uses: actions/setup-python@v5

#       - name: Upload artifacts
#         env:
#           # Secret variables need to be mapped to environment variables explicitly
#           SCIKIT_LEARN_NIGHTLY_UPLOAD_TOKEN: ${{ secrets.SCIKIT_LEARN_NIGHTLY_UPLOAD_TOKEN }}
#           SCIKIT_LEARN_STAGING_UPLOAD_TOKEN: ${{ secrets.SCIKIT_LEARN_STAGING_UPLOAD_TOKEN }}
#           ARTIFACTS_PATH: dist
#         # Force a replacement if the remote file already exists
#         run: bash build_tools/github/upload_anaconda.sh